      logging:
        level:
          com.netflix.discovery: DEBUG
          org.springframework.cloud.netflix.eureka: DEBUG
server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG