spring:
  application:
    name: gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /timeforge/users/$\{segment}

        - id: goals
          uri: lb://goal-service
          predicates:
            - Path=/goals/**
          filters:
            - RewritePath=/goals/(?<segment>.*), /timeforge/goals/$\{segment}

        - id: collaborations
          uri: lb://collaboration-service
          predicates:
            - Path=/collaborations/**
          filters:
            - RewritePath=/collaborations/(?<segment>.*), /timeforge/collaborations/$\{segment}

        - id: projects
          uri: lb://project-service
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects/(?<segment>.*), /timeforge/projects/$\{segment}

        - id: workspaces
          uri: lb://workspaces-service
          predicates:
            - Path=/workspaces/**
          filters:
            - RewritePath=/workspaces/(?<segment>.*), /timeforge/workspaces/$\{segment}

        - id: ml-service
          uri: lb://ml-service
          predicates:
            - Path=/ml/**
          filters:
            - RewritePath=/ml/(?<segment>.*), /$\{segma

  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: gateway-server
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,routes
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0