eureka:
  instance:
    hostname: goal-service
    instance-id: ${spring.application.name}:${server.port}
    appname: goal-service
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
    prefer-ip-address: false
    metadata-map:
      zone: primary  # Helps with load balancing
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Add these new properties:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 3


server:

  port: 8200
  servlet:
    context-path: /timeforge

spring:
  application:
    name: goals  # Correction du nom de l'application

  # Configuration MongoDB
  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongo:27017/timeforge?authSource=admin  # Updated
      database: timeforge

  # Niveau de log pour MongoDB
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
          probability: 1.0

  # Configuration du serveur de l'application

# Exclure l'autoconfiguration JDBC car on utilise MongoDB


application:
  config:
    users-url: http://localhost:8222/users


management:
  tracing:
    sampling:
      probability: 1.0
