eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}  # Unique ID
    appname: user-service
    lease-renewal-interval-in-seconds: 3  # More aggressive
    lease-expiration-duration-in-seconds: 9
    prefer-ip-address: false
    metadata-map:
      zone: primary  # Helps with load balancing

  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    # Add these new properties:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 3

server:
  port: 8100
  servlet:
    context-path: /timeforge

spring:
  application:
    name: users
  config:
    activate:
      on-profile: docker
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongo:27017/timeforge?authSource=admin
      database: users
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG
