eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    appname: workspaces-service
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
    prefer-ip-address: false
    hostname: workspaces-service
    metadata-map:
      zone: primary

  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 3



server:
  port: 8500
  servlet:
    context-path: /timeforge

spring:
  application:

    name: workspaces

  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongo:27017/timeforge?authSource=admin  # Updated
      database: timeforge
  logging:
    level:
      org.springframework.data.mongodb.core: DEBUG
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration