spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8600/realms/timeforge
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8600

jwt:
  auth:
    converter:
      resource-id: time-forge-rest-api
      principle-attribute: preferred_username
