spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users  # Make sure the name is correct
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 474610756884-0lui56qp0jkv53rl45trhgpsqcc520p2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
            scope:
              - user:email
              - read:user
brevo:
  api-key: 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
  sender-email: hassenemansouri35@gmail.com
  sender-name: App

frontend:
  url: http://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
paymee:
  api:
    url: https://sandbox.paymee.tn/api/v2
    token: ${PAYMEE_API_TOKEN:61934b9ebdcc105bc73be88da52b3fd5e9c920fb}
    redirect-timeout: 5000 # milliseconds
  urls:
    return-url: ${FRONTEND_URL:http://localhost:4200}/payment/success
    cancel-url: ${FRONTEND_URL:http://localhost:4200}/payment/cancel
    webhook-url: ${BACKEND_URL:http://localhost:8080}/api/payments/webhook
  test:
    phone: "11111111"
    password: "11111111"


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG