spring:
  application:
    name: users
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: docker
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongo:27017/users?authSource=admin
brevo:
  api-key: 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
  sender-email: hassenemansouri35@gmail.com
  sender-name: App

frontend:
  url: http://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
flouci:
  app_token: "a1e1cfab-f9b8-47ae-8145-05ec72d950ad"
  app_secret: "933d642f-9478-417d-b575-601b23e07105"
  developer_tracking_id : "fdaae6d7-dd05-4cbc-8f0b-226476c1d920"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.your pzackage: DEBUG