spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: workspaces
  main:
    allow-bean-definition-overriding: true
  web:
    cors:
          allowed-origins: "http://localhost:4200"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
  data:
    mongodb:
          uri: mongodb://localhost:27017/timeforge
          database: timeforge
  logging:
    level:
      org.springframework: DEBUG
      tn.esprit: DEBUG
      org.springframework.data.mongodb.core: DEBUG
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure: DEBUG


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    compatibility-verifier:
          enabled: false
  mvc:
    log-request-details: true

management:
  tracing:
    sampling:
      probability: 0.0



logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
