spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: workspaces
  main:
    allow-bean-definition-overriding: true
  web:
    cors:
          allowed-origins: "http://localhost:4200"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
  data:
    mongodb:
          uri: mongodb://localhost:27017/timeforge
          database: timeforge
  logging:
    level:
      org.springframework: DEBUG
      tn.esprit: DEBUG
      org.springframework.data.mongodb.core: DEBUG
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure: DEBUG


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    compatibility-verifier:
          enabled: false
  mvc:
    log-request-details: true
  servlet:
    multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB

management:
  tracing:
    sampling:
      probability: 0.0



logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com:
      twilio: DEBUG
    org:
      springframework:
              web:
                multipart: DEBUG
              apache:
              tomcat:
                util:
                  http:
                    fileupload: DEBUG

twilio:
  account:
    sid: AC05c9b78bce2f77e9d43cdf68154fb9d1
  auth:
    token: a4ded814d7a028d485cf55dd8a1a995a
  phone:
    number: +19516678378


file:
  path: uploads




